services:
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - .data/redis:/data

  postgres:
    image: ghcr.io/baosystems/postgis:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "main"
      POSTGRES_DB: "main"
    volumes:
      - .data/postgres:/var/lib/postgresql
#      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


#  kafka:
#    image: confluentinc/cp-kafka:7.6.1
#    ports:
#      - "29092:29092"
#    environment:
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_NODE_ID: 1
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
#      KAFKA_NUM_PARTITIONS: 5
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#    volumes:
#      - ./docker/data/kafka:/var/lib/kafka/data
#    healthcheck:
#      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:v0.7.2
#    depends_on:
#      - kafka
#    ports:
#      - "9080:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA
#    volumes:
#      - ./docker/data/kafka_ui:/etc/kafkaui/dynamic_config.yaml

